# Generated by Django 5.0.6 on 2026-09-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('arquivo', models.FileField(upload_to='arquivos/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
